### ISSUE TITLE
.name to be in lowercase?

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-just#1]
why it is uppercased?

**Comment by ForbesLindesay** [comment]
Because that's how they write it in their readme (https://github.com/baryshev/just).  The name is really just for logs and error messages, so it should match the case that's generally used when people put that transformer name in a sentence.

**Comment by tunnckoCore** [comment]
hm.

**Comment by RobLoach** [comment]
We're using lowercase for all other `.name` values, however. We should likely use lowercase `just` for the `.name`. See #2.
